### ISSUE TITLE
Compute allele counts error

### ISSUE THREAD

**Issue by mahmood225** [popgenmethods/momi2#46]
Hi all,
I'm using my data to calculate allele counts  according to tutorial (https://momi2.readthedocs.io/en/latest/tutorial.html).
I prepared my data for this analyses using Plink (for VCF files for each chromosomes separately) followed by these codes:
_**bgzip -c 1.vcf > 1.vcf.gz
tabix 1.vcf.gz**_
 and then and tried to run them exactly like the tutorial using the following codes
_**%%sh
for chrom in `seq 1 31`;
do
python -m momi.read_vcf \
data/$chrom.vcf.gz data/pop.txt \
data/$chrom.snpAlleleCounts.gz \
--bed data/$chrom.bed
done**_
But I faced with this error:
_**Traceback (most recent call last):
  File "/home/mahmoud/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mahmoud/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mahmoud/anaconda3/lib/python3.8/site-packages/momi/read_vcf.py", line 42, in <module>
    SnpAlleleCounts.read_vcf(
  File "/home/mahmoud/anaconda3/lib/python3.8/site-packages/momi/data/snps.py", line 96, in read_vcf
    bcf_in.subset_samples(list(ind2pop.keys()))
  File "pysam/libcbcf.pyx", line 4455, in pysam.libcbcf.VariantFile.subset_samples
  File "pysam/libcbcf.pyx", line 2032, in pysam.libcbcf.VariantHeader._subset_samples
ValueError: missing 177 requested samples
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-12-b84326ab3006> in <module>
----> 1 get_ipython().run_cell_magic('sh', '', 'python -m momi.read_vcf data/1.vcf.gz data/pop.txt data/1.snpAlleleCounts.gz --bed data/1.bed\n')

~/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2397             with self.builtin_trap:
   2398                 args = (magic_arg_s, cell)
-> 2399                 result = fn(*args, **kwargs)
   2400             return result
   2401 

~/anaconda3/lib/python3.8/site-packages/IPython/core/magics/script.py in named_script_magic(line, cell)
    140             else:
    141                 line = script
--> 142             return self.shebang(line, cell)
    143 
    144         # write a basic docstring:

~/anaconda3/lib/python3.8/site-packages/decorator.py in fun(*args, **kw)
    229             if not kwsyntax:
    230                 args, kw = fix(args, kw, sig)
--> 231             return caller(func, *(extras + args), **kw)
    232     fun.__name__ = func.__name__
    233     fun.__doc__ = func.__doc__

~/anaconda3/lib/python3.8/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3/lib/python3.8/site-packages/IPython/core/magics/script.py in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'python -m momi.read_vcf data/1.vcf.gz data/pop.txt data/1.snpAlleleCounts.gz --bed data/1.bed\n'' returned non-zero exit status 1.**_

Could you please help me to solve this error?

Thanks

**Comment by jackkamm** [comment]
Hi @mahmood225 , very sorry for the long delay in response.

The error messages says it can't find the sample names in the VCF. So, I would guess there's some mismatch between the sample names in your `pop.txt` file and the VCF.

If you can send the pop.txt and a small version of the VCF, I can take a look. I promise, it won't take so long for me to respond next time.

Best,
Jack

**Comment by mahmood225** [comment]
Hi @jackkamm 
Thank you so much for your reply.
You were right about the sample name issue. I fixed the sample names and run the codes again. But I faced with a new error repeated in the same number of my chromosomes (n=31) that is:
**> No valid SNPs read! Try setting ancestral_alleles=False.**

I also could not see **_sfs.gz_** file in the output, so I remained at this step. 
Is this due to using unphased genotype? if so, can I used for example the Beagle software?

you can see VCF file for chromosome 1 here:
[chr1.vcf.gz](https://github.com/popgenmethods/momi2/files/7785242/chr1.vcf.gz)
and my pop information here:
[pop.txt](https://github.com/popgenmethods/momi2/files/7785243/pop.txt)

**Comment by jackkamm** [comment]
By default momi uses the unfolded SFS which requires specifying the ancestral allele. It looks for it in a "AA" INFO field in the VCF, unless you specify an outgroup in which case it takes the AA from that population. Alternatively, you can tell momi to use the folded SFS which doesn't require an ancestral allele. So, here are your options:

1. Tell momi to use the folded SFS, by passing the `--no_aa` option
2. Add an AA field to the INFO column of your VCF
3. Specify some population to be an outgroup and specify it with the `--outgroup` option.

You can see the various options by calling `python -m momi.read_vcf --help`.
